### ISSUE TITLE
Peer to peer code review by Team-65-the-Labradors

### ISSUE THREAD

**Issue by euqueme** [AlfredoElizarraras/Private-events#1]
Hello Oscar and Carlos :service_dog: 

Congratulations! your project looks great and works very well, we only have some suggestions about where to put the code:

1. Use partials to render repetitive code and to remove logic from Views
2. It is not necessary to render String variables with HTML code for that you could use partials or you could use loops within views that's not a bad practice and it's actually more understandable
3. we strongly suggest displaying your flash messages for errors in the application.html.erb instead of doing it in each view to avoid repeating yourself and keep your code DRY

That's it! :raised_hands: 

Keep up the good work :medal_sports: :medal_sports:

**Comment by Flakster** [comment]
Thanks for your feedback @euqueme  It helped us a lot
