### ISSUE TITLE
## Fix show of private events

### ISSUE THREAD

**Issue by AlfredoElizarraras** [AlfredoElizarraras/Private-events#12]
- [x] Fix if the user type manually the route of a private event, he are not supposed to have access that page.

**Comment by AlfredoElizarraras** [comment]
Add a helper method to redirect the user if he or she is not in the invited list of the event. :bug: 
The changes can be seen in the following links. :eyes: 
- ce3ba115e7d30dbf8ba18f1c796b8cfd15d27421 - Fix show permissions.
- 5f75891caea867b5c4cffd938b4281a4ba270e9d - Refactor the helper method.

**Comment by Flakster** [comment]
Now the public events can be seen by all the users, even anonymous ones. See the change here: :eyes:  c5fb37a7449d3c23000a1bd7d89064f696badb2d
