### ISSUE TITLE
Peer to peer code review by Team-65-The-Labradors

### ISSUE THREAD

**Issue by euqueme** [AlfredoElizarraras/Private-events#17]
# Peer to peer code review: Team-65-The-Labradors :service_dog: 

Hello Oscar and Carlos :wave:

Great job so far, your project looks very professional and you've managed to handle eager loading very well so you should feel very proud of yourselves :medal_sports: :medal_sports: 

I only have one suggestion:  to make your `create` method in the Event `controller` less crowded put the date formatting code that you have in your` @event.date` in a private method

That's all so far :clap:

Continue a great job :100:

**Comment by Flakster** [comment]
Thanks for your suggestion @euqueme . We have moved the time formatting logic to a private method! :+1: 
The changes can be seen here: 0176a11aff9dd764e9466fa1e721eb9e70fa74fe
