### ISSUE TITLE
May 14, 2020 | Code-Review : The Poodles 

### ISSUE THREAD

**Issue by Meltrust** [AlfredoElizarraras/Private-events#2]
Nice start. Keep it up!

**Comment by Samkiroko** [comment]
- nice work 
- remember to sort out the private event

**Comment by AlfredoElizarraras** [comment]
Hello, thanks for your feedback. :wave:

We have implemented the sort, to show the corresponding events based on it's accessibility either private or public. :male_detective: 

You can see the changes in the next link: d81c561cd09ad75b1cbb9155546f3a06b077c7ce :eyes:
