### ISSUE TITLE
## Add the capability to the users decline or accept the invitation to events

### ISSUE THREAD

**Issue by Flakster** [AlfredoElizarraras/Private-events#9]
- [x] List invitations for the invitee for each host

**Comment by AlfredoElizarraras** [comment]
We add a new view with the notifications (invitations) for the users, it is showing the invitations that are pending to accept or decline. Also it is showing in the nav bar the number of notifications that we have.
The changes can be seen in the next commits:
- 5aafc30ae379ab277b32794c719265818a68d474 - Display number of notifications and accept link.
- 3406bfcb14023649796f889a35924d7e6f3a3d1b - Display decline link.

**Comment by AlfredoElizarraras** [comment]
When the page loads the user's notification page takes time to load because the n + 1 problem.
- e2a6edd84ae37205258fa70a9b2459c03e81e81a - Fix using join in the invitation model.

**Comment by AlfredoElizarraras** [comment]
The notifications were displaying 2 times and also were not displaying notifications for upcoming events. :bug: 
- 31bb6023fe99e635a1ab3c303817e145029771f8 - Fix queries.
